The story so far

diff --git a/Makefile.example b/Makefile.example
--- a/Makefile.example
+++ b/Makefile.example
@@ -1,19 +1,60 @@
 ##
 # Run make targets using the ubuntudesign/devrun image.
 # You can see a list of the commands in the image here:
-# TODO: Add Git URL
+# https://github.com/ubuntudesign/devrun/tree/master/bin
 ##
 
 # Tell ubuntudesign/devrun where to find docker
 # Based on https://github.com/docker/compose/releases/download/1.7.1/run.sh
 ifeq ($(DOCKER_HOST),)
 	DOCKER_HOST := /var/run/docker.sock
-	DOCKER_ADDR := -v "$(DOCKER_HOST)":"$(DOCKER_HOST)" -e DOCKER_HOST
+	DOCKER_ADDR := --volume "$(DOCKER_HOST)":"$(DOCKER_HOST)" --env DOCKER_HOST
 else
-	DOCKER_ADDR := -e DOCKER_HOST -e DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH
+	DOCKER_ADDR := --env DOCKER_HOST --env DOCKER_TLS_VERIFY --env DOCKER_CERT_PATH
 endif
 
-.DEFAULT_GOAL := help
+define DEVRUN
+docker run \
+  ${DOCKER_ADDR} ${COMPOSE_OPTIONS} \
+  --tty --interactive \
+  --volume "`pwd`":"`pwd`" \
+  --workdir "`pwd`" \
+  --env-file .env $(patsubst %,--env PORT=%,$(PORT))  \
+  devrun
+endef
+
+define DOCKER_MISSING
+Error: Docker not installed
+==
+
+Please install Docker before continuing:
+https://docs.docker.com/engine/installation/
+
+endef
+
+define NOT_IN_GROUP
+Error: User not in docker group
+===
+
+Please add this user to the docker group, e.g. with:
+$$ newgrp docker
+
+endef
+
+export GROUP_MESSAGE INSTALL_MESSAGE
+
+.DEFAULT_GOAL := commands
+
+check-for-docker:
+	@if ! command -v docker >/dev/null 2>&1 || ! grep -q '^docker:' /etc/group; then \
+	    echo >&2 "$$DOCKER_MISSING"; \
+	    exit 1; \
+	fi
+	@if ! groups | grep -q '\bdocker\b'; then \
+	    echo "$$NOT_IN_GROUP"; \
+	    exit 1; \
+	fi
 
 %:
-	@docker run --rm -ti ${DOCKER_ADDR} ${COMPOSE_OPTIONS} -v $(shell pwd):$(shell pwd) -w "$(shell pwd)" ubuntudesign/devrun "$@"
+	@${MAKE} --quiet check-for-docker
+	@${DEVRUN} $@
